### ISSUE TITLE
Bad with matrix dot calculation 

### ISSUE THREAD

**Issue by rbelanec** [gooeyone/cuda-neural-network#2]
Hello,

first of all. I am really grateful, this simple MLP implemtation really helped me with understanding of the whole NN concept.

But I believe I found a mistake in your matrix multiplication implementation [here ](https://github.com/pwlnk/cuda-neural-network/blob/master/cuda-neural-network/src/layers/linear_layer.cu) at line 23. I think there is a typo A_x_dim should be A_y_dim or W_x_dim should be W_y_dim .

Thanks.

**Comment by pwlnk** [comment]
Hi Róbert,

thank you for your message, I'm really happy you find it helpful!

Regarding the mistake. It seems fine to me, as we multiply each row-element
of W matrix with each col-element of A matrix. I think the most important
fact here is that in the memory data are stored row-wise within those
matrices, so in each iteration to compute proper index we need first go to
a proper row in a matrix and then to a proper column. We go to proper row
by taking multiples of x_dim and then add a column index.

For the W matrix we have W[row * W_x_dim + i], so each time we land in the
same row and just go to valid column with i.
For the A matrix we have A[i * A_x_dim + col], so each time we land in i'th
row and go each time to the same column with col.

Kind regards,
Paweł L.

niedz., 20 gru 2020 o 22:51 Róbert Belanec <notifications@github.com>
napisał(a):

**Comment by rbelanec** [comment]
Hello Paweł,

thank you very much for your answer and explanation. Now its much clearer for me.

Best regards,
Robert Belanec
