### ISSUE TITLE
How to open this project with Eclipse Nsight

### ISSUE THREAD

**Issue by fPecc** [gooeyone/cuda-neural-network#3]
I would like to open, compile and run this project using the NVIDIA Nsight Eclipse IDE, but I cannot seem to find the correct way to create a project from the sources of this project.

Could you provide a step by step guide to do it?

Thanks!

**Comment by pwlnk** [comment]
Directories `cuda-neural-network` and `cuda-neural-network-test` contains Eclipse project files. You just need to import them in IDE.

**Comment by fPecc** [comment]
Thanks, sorry for the simple question, it was just that easy :D

**Comment by pwlnk** [comment]
No problem ;)
